name: Build and deploy webpage
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
      - name: Install Node/NPM
        uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '12.x'
      - name: Cache npm
        uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-    
      - name: Build
        run: |
          npm ci
          npm run build_deploy
      - name: Create file 404
        run: | 
          cp ./dist/app/index.html ./dist/app/404.html
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: angular_alexsanro_portoflio
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Dowload artifcat
      uses: actions/download-artifact@v1
      with:
        name: angular_alexsanro_portoflio
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy to Repository
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: master
        FOLDER: angular_alexsanro_portoflio/app
        REPOSITORY_NAME: alexsanro/alexsanro.github.io
        TARGET_FOLDER: .
  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get version
      run: |
        VERSION=$(npm run env | grep npm_package_version | cut -d '=' -f 2)
        echo ::set-env name=VERSION::$VERSION  
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: "[Bumped Version] ${{ env.VERSION }}"
        draft: false
        prerelease: false
